// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: protobuf/patent.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PatentSvrClient is the client API for PatentSvr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PatentSvrClient interface {
	GetPatentResult(ctx context.Context, in *GetPatentResultRequest, opts ...grpc.CallOption) (*GetPatentResultReply, error)
}

type patentSvrClient struct {
	cc grpc.ClientConnInterface
}

func NewPatentSvrClient(cc grpc.ClientConnInterface) PatentSvrClient {
	return &patentSvrClient{cc}
}

func (c *patentSvrClient) GetPatentResult(ctx context.Context, in *GetPatentResultRequest, opts ...grpc.CallOption) (*GetPatentResultReply, error) {
	out := new(GetPatentResultReply)
	err := c.cc.Invoke(ctx, "/patentpb.PatentSvr/GetPatentResult", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatentSvrServer is the server API for PatentSvr service.
// All implementations must embed UnimplementedPatentSvrServer
// for forward compatibility
type PatentSvrServer interface {
	GetPatentResult(context.Context, *GetPatentResultRequest) (*GetPatentResultReply, error)
	mustEmbedUnimplementedPatentSvrServer()
}

// UnimplementedPatentSvrServer must be embedded to have forward compatible implementations.
type UnimplementedPatentSvrServer struct {
}

func (UnimplementedPatentSvrServer) GetPatentResult(context.Context, *GetPatentResultRequest) (*GetPatentResultReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPatentResult not implemented")
}
func (UnimplementedPatentSvrServer) mustEmbedUnimplementedPatentSvrServer() {}

// UnsafePatentSvrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatentSvrServer will
// result in compilation errors.
type UnsafePatentSvrServer interface {
	mustEmbedUnimplementedPatentSvrServer()
}

func RegisterPatentSvrServer(s grpc.ServiceRegistrar, srv PatentSvrServer) {
	s.RegisterService(&PatentSvr_ServiceDesc, srv)
}

func _PatentSvr_GetPatentResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPatentResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatentSvrServer).GetPatentResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/patentpb.PatentSvr/GetPatentResult",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatentSvrServer).GetPatentResult(ctx, req.(*GetPatentResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PatentSvr_ServiceDesc is the grpc.ServiceDesc for PatentSvr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PatentSvr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "patentpb.PatentSvr",
	HandlerType: (*PatentSvrServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPatentResult",
			Handler:    _PatentSvr_GetPatentResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/patent.proto",
}
