// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.12.4
// source: protobuf/patent.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPatentResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetPatentResultRequest) Reset() {
	*x = GetPatentResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_patent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPatentResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatentResultRequest) ProtoMessage() {}

func (x *GetPatentResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_patent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatentResultRequest.ProtoReflect.Descriptor instead.
func (*GetPatentResultRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_patent_proto_rawDescGZIP(), []int{0}
}

func (x *GetPatentResultRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetPatentResultReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *GetPatentResultReply) Reset() {
	*x = GetPatentResultReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_patent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPatentResultReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatentResultReply) ProtoMessage() {}

func (x *GetPatentResultReply) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_patent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatentResultReply.ProtoReflect.Descriptor instead.
func (*GetPatentResultReply) Descriptor() ([]byte, []int) {
	return file_protobuf_patent_proto_rawDescGZIP(), []int{1}
}

func (x *GetPatentResultReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_protobuf_patent_proto protoreflect.FileDescriptor

var file_protobuf_patent_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x70, 0x61, 0x74, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x61, 0x74, 0x65, 0x6e, 0x74, 0x70,
	0x62, 0x22, 0x2c, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22,
	0x30, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x32, 0x62, 0x0a, 0x09, 0x50, 0x61, 0x74, 0x65, 0x6e, 0x74, 0x53, 0x76, 0x72, 0x12, 0x55,
	0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x61, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x20, 0x2e, 0x70, 0x61, 0x74, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74,
	0x50, 0x61, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x61, 0x74, 0x65, 0x6e, 0x74, 0x70, 0x62, 0x2e, 0x47,
	0x65, 0x74, 0x50, 0x61, 0x74, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x49, 0x0a, 0x0f, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x61, 0x6c,
	0x6c, 0x2e, 0x70, 0x61, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x0b, 0x50, 0x61, 0x74, 0x65, 0x6e, 0x74,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x36, 0x30, 0x34, 0x32, 0x35, 0x34, 0x32, 0x32, 0x39, 0x2f, 0x70, 0x61,
	0x74, 0x65, 0x6e, 0x74, 0x5f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_patent_proto_rawDescOnce sync.Once
	file_protobuf_patent_proto_rawDescData = file_protobuf_patent_proto_rawDesc
)

func file_protobuf_patent_proto_rawDescGZIP() []byte {
	file_protobuf_patent_proto_rawDescOnce.Do(func() {
		file_protobuf_patent_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_patent_proto_rawDescData)
	})
	return file_protobuf_patent_proto_rawDescData
}

var file_protobuf_patent_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_patent_proto_goTypes = []interface{}{
	(*GetPatentResultRequest)(nil), // 0: patentpb.GetPatentResultRequest
	(*GetPatentResultReply)(nil),   // 1: patentpb.GetPatentResultReply
}
var file_protobuf_patent_proto_depIdxs = []int32{
	0, // 0: patentpb.PatentSvr.GetPatentResult:input_type -> patentpb.GetPatentResultRequest
	1, // 1: patentpb.PatentSvr.GetPatentResult:output_type -> patentpb.GetPatentResultReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_patent_proto_init() }
func file_protobuf_patent_proto_init() {
	if File_protobuf_patent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_patent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPatentResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_patent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPatentResultReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_patent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_patent_proto_goTypes,
		DependencyIndexes: file_protobuf_patent_proto_depIdxs,
		MessageInfos:      file_protobuf_patent_proto_msgTypes,
	}.Build()
	File_protobuf_patent_proto = out.File
	file_protobuf_patent_proto_rawDesc = nil
	file_protobuf_patent_proto_goTypes = nil
	file_protobuf_patent_proto_depIdxs = nil
}
